---

- name: set facts
  set_fact:
    role_comment: "( {{ docker_container_name | default('selenium-grid') }} )"
  tags:
    - always

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    published_ports: "{{ docker_published_ports }}"
    volumes: "{{ docker_volumes }}"
    docker_host: "{{ docker_host }}"
    shm_size: "{{ docker_shm_size }}"
    env: "{{ docker_env }}"
    healthcheck: "{{ grid_healthcheck }}"
  tags:
    - docker-container

- name: wait until service is ready {{ role_comment }} @ {{ grid_status_url }}
  uri:
    url: "{{ grid_status_url }}"
    return_content: true
    timeout: 5
  register: console
  until: grid_status_ready in console.content
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
  tags:
    - docker-container
