---

- name: set facts
  set_fact:
    role_comment: "( {{ docker_container_name | default('selenium-grid') }} )"
  tags:
    - always

- name: ensure container is started {{ role_comment }}
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}{% if docker_image %}:{% endif %}{{ docker_image_tag }}"
    published_ports: "{{ docker_published_ports }}"
    env:
      TZ: "{{ docker_timezone }}"
      GRID_TIMEOUT: "{{ service_selenium_grid_timeout | default(10) }}"
  tags:
    - docker-container

- name: wait until service is ready {{ role_comment }} http://{{ service_selenium_grid_host }}:{{ service_selenium_grid_http_port }}/wd/hub/status
  uri:
    url: "http://{{ service_selenium_grid_host }}:{{ service_selenium_grid_http_port }}/wd/hub/status"
    return_content: true
    timeout: 300
  register: service_console
  until: (service_console.content.find("Hub has capacity") != -1) or (service_console.content.find("No spare hub capacity") != -1)
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
  tags:
    - docker-container
